{
 "title": "ilo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ilo_ident", "label": "ILO Identifier", "query": "instance" },
   {
    "name": "node",
    "label": "ILO",
    "query": {
     "query": "label_values(ilo_exporter_scrape_failures_total,$ilo_ident)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter failures",
   "type": "stat",
   "description": "Number of failed scrapes within the current time range.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ilo_exporter_scrape_failures_total{$ilo_ident=~\"$node\"}[$__range])",
     "legendFormat": "SNMP failures"
    },
    {
     "expr": "increase(ilo_exporter_https_failures_total{$ilo_ident=~\"$node\"}[$__range])",
     "legendFormat": "HTTPS failures"
    }
   ]
  },
  {
   "title": "Drive health summary",
   "type": "stat",
   "description": "A summary of drive health. Drives with bad health will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(condition) (ilo_drive_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "stat",
   "description": "The total power draw reported by the ILO(s) in watts.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_server_power_draw{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}]"
    }
   ]
  },
  {
   "title": "Temperature summary",
   "type": "stat",
   "description": "A summary of temperature status. Bad temperature statuses will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(condition) (ilo_temperature_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "CPU health summary",
   "type": "stat",
   "description": "A summary of CPU health. Unhealthy CPUs will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (ilo_cpu_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Fan health summary",
   "type": "stat",
   "description": "A summary of fan health. Unhealthy fans will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(condition) (ilo_fan_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Memory health summary",
   "type": "stat",
   "description": "A summary of memory health. Memory modules in bad health will add new red numbers to this display, labeled appropriately.\n\nMemory modules with status \"notPresent\" are hidden.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(condition) (ilo_memory_info{$ilo_ident=~\"$node\", status!=\"notPresent\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Drive status summary",
   "type": "stat",
   "description": "A summary of drive status. Drives with status other than \"Ok\" will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (ilo_drive_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Crossed Temperature thresholds",
   "type": "stat",
   "description": "The number of currently crossed temperature thresholds.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((ilo_temperature_celsius{$ilo_ident=~\"$node\"} > on($ilo_ident, id) (ilo_temperature_threshold{$ilo_ident=~\"$node\"} > 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU summary",
   "type": "stat",
   "description": "A generalization of the combined CPU power your server(s). \n\nThis doesn't mean much on its own, but it looks cool.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ilo_cpu_cores_enabled{$ilo_ident=~\"$node\"})",
     "legendFormat": "total cores"
    },
    {
     "expr": "sum(ilo_cpu_threads_available{$ilo_ident=~\"$node\"})",
     "legendFormat": "total threads"
    },
    {
     "expr": "sum(ilo_cpu_speed{$ilo_ident=~\"$node\"} * on($ilo_ident, id) ilo_cpu_threads_available{$ilo_ident=~\"$node\"})",
     "legendFormat": "total rate"
    }
   ]
  },
  {
   "title": "Fan presence summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(presence) (ilo_fan_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{presence}}"
    }
   ]
  },
  {
   "title": "Memory status summary",
   "type": "stat",
   "description": "A summary of memory status. Memory modules with status other than \"good\" or \"notPresent\" or \"spare\" will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (ilo_memory_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Drive SMART summary",
   "type": "stat",
   "description": "A summary of drive SMART status. Drives with bad SMART status will add new red numbers to this display, labeled appropriately.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(smart_status) (ilo_drive_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "The total power draw reported by the ILO(s) in watts.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ilo_server_power_draw{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}]"
    }
   ]
  },
  {
   "title": "Ambient temperature",
   "type": "stat",
   "description": "Ambient temperature averaged across all nodes.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ilo_temperature_celsius{$ilo_ident=~\"$node\", id=\"1\"})",
     "legendFormat": "[{{$ilo_ident}}]"
    }
   ]
  },
  {
   "title": "Fan speed summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(speed) (ilo_fan_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "{{speed}}"
    }
   ]
  },
  {
   "title": "Memor summary",
   "type": "stat",
   "description": "A generalization of the combined memory capacity of your server(s). \n\nThis doesn't mean much on its own, but it looks cool.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ilo_memory_size{$ilo_ident=~\"$node\"})",
     "legendFormat": "total memory"
    }
   ]
  },
  {
   "title": "Drive summary",
   "type": "stat",
   "description": "A generalization of the combined drive capacity of your server(s). \n\nThis doesn't mean much on its own, but it looks cool.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ilo_drive_size{$ilo_ident=~\"$node\"})",
     "legendFormat": "total disk"
    }
   ]
  },
  {
   "title": "Maximum temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ilo_temperature_celsius{$ilo_ident=~\"$node\"})",
     "legendFormat": "[{{$ilo_ident}}]"
    }
   ]
  },
  {
   "title": "Maximum fan speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ilo_fan_speed{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(locale) ilo_fan_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "max speed"
    },
    {
     "expr": "avg(ilo_fan_speed{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(locale) ilo_fan_info{$ilo_ident=~\"$node\"})",
     "legendFormat": "avg speed"
    }
   ]
  },
  { "title": "temperature details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature stats",
   "type": "stat",
   "description": "Temperature of each sensor. \n\nNOTE: The color shown is a generalization, and not representative of whether the temperature has exceeded thresholds.",
   "gridPos": { "h": 24, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(label) ilo_temperature_info{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}] {{label}}"
    }
   ]
  },
  {
   "title": "Temperature Threshold Proximity",
   "type": "heatmap",
   "description": "Temperature represented as a percentage of the provided temperature threshold.\n\nThis can be used to identify sensors that are closest to or have already crossed said threshold.",
   "gridPos": { "h": 24, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "(ilo_temperature_celsius{$ilo_ident=~\"$node\"} / on($ilo_ident, id) (ilo_temperature_threshold{$ilo_ident=~\"$node\"} > 0)) * on($ilo_ident, id) group_left(label, threshold_type) ilo_temperature_info{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}] {{threshold_type}} - {{label}}"
    }
   ]
  },
  {
   "title": "Temperature Sensor Info",
   "type": "table",
   "description": "Detailed information about every reported temperature sensor.",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "label_join(label_join(ilo_temperature_info{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\"), \"ilo\", \",\", \"$ilo_ident\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_temperature_celsius{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_temperature_threshold{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_temperature_celsius{$ilo_ident=~\"$node\"} / on(job, instance, id, sensor_locale) ilo_temperature_threshold{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature map",
   "type": "xychart",
   "description": "Temperatures plotted on an x/y graph, similar to the 2d temperature graph in the ILO control panel.",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 42 },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(x_pos, y_pos, label, sensor_locale, condition, threshold_type) ilo_temperature_info{$ilo_ident=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "A graph showing the temperatures of various sensors over time.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(label) ilo_temperature_info{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}] {{label}}"
    }
   ]
  },
  { "title": "fan details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "description": "A graph of various fan speeds over time.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ilo_fan_speed{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(locale) ilo_fan_info{$ilo_ident=~\"$node\"}",
     "legendFormat": "[{{$ilo_ident}}] {{locale}} fan {{id}}"
    }
   ]
  },
  {
   "title": "fan info",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "label_join(label_join(ilo_fan_info{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\", \"id\"), \"ilo\", \",\", \"$ilo_ident\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_fan_speed{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\", \"id\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "cpu details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "CPU info",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "label_join(label_join(ilo_cpu_info{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\"), \"ilo\", \",\", \"$ilo_ident\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_cpu_speed{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_cpu_step{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_cpu_cores_enabled{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_cpu_threads_available{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "drive details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "drive info",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "label_join(label_join(ilo_drive_info{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\"), \"ilo\", \",\", \"$ilo_ident\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_drive_size{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_drive_temperature{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_drive_temperature_threshold{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_drive_temperature_maximum{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_drive_reference_time{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\",\"id\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "drive temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "255 > (ilo_drive_temperature{$ilo_ident=~\"$node\"} * on($ilo_ident, id) group_left(port, box, bay, vendor, serial) ilo_drive_info{$ilo_ident=~\"$node\"}) > 0",
     "legendFormat": "[{{$ilo_ident}}] ({{port}}, {{box}}, {{bay}}) - {{vendor}} {{serial}}"
    }
   ]
  },
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "memory info",
   "type": "table",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "label_join(label_join(ilo_memory_info{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\", \"id\"), \"ilo\", \",\", \"$ilo_ident\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(ilo_memory_size{$ilo_ident=~\"$node\"}, \"identifier\", \",\", \"$ilo_ident\", \"id\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}